### ISSUE TITLE
Support multiple (non-best) chains, concurrent reads on different forks.

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcdb#6]
The database currently only saves the best chain.  If a fork extends beyond the current best chain, the reorged blocks will be removed from the database.  This makes the database unsafe for multiple callers who concurrently expect their given block range to be valid.

For example, when btcd must rescan some range of blocks, and the tip of the range is removed from the best chain due to a new best block,   db lookups will begin failing for missing the block for some hash, or worse (if only heights are used), lookups will silently continue with no indication that previously processed blocks may not be on the same fork.

A better solution would be to use an iterator which allows walking  through some range of blocks in a fork.  Even if the best chain is switched, these blocks can still be iterated over.  After the iteration is finished, the caller can finish (it returned results about the chain at the time the request was made) or a switch back to the main chain and/or best block can be made if more blocks were attached.

**Comment by davecgh** [comment]
This has been moved to btcsuite/btcd#255.
