### ISSUE TITLE
BlockShaMissing should include the missing block hash

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcdb#7]
The BlockShaMissing error is not very descriptive when printed, due to the missing block sha not being included in the error string.  To fix this, BlockShaMissing should be changed to a type rather than just a variable.  For example:

```Go
type BlockShaMissing btcwire.ShaHash

func (e *BlockShaMissing) Error() string {
        return "block " + (*btcwire.ShaHash)(e).String() + " missing"
}
```

**Comment by davecgh** [comment]
This has been moved to btcsuite/btcd#256.
