### ISSUE TITLE
Remove Db.DropAfterBlockBySha and Db.RollbackClose

### ISSUE THREAD

**Issue by jongillham** [btcsuite/btcdb#9]
I would like to remove [Db.DropAfterBlockBySha](https://github.com/conformal/btcdb/blob/master/db.go#L40) and [Db.RollbackClose](https://github.com/conformal/btcdb/blob/master/db.go#L111) as it prohibits several NoSQL datastores from using btcd due to their lax transaction/atomicity guarantees and no concept of rollback.

I just wanted to start a discussion on how feasible this would be and what the implications are before I dive in and break everything.

**Comment by davecgh** [comment]
This has been moved to btcsuite/btcd#257.
